module.exports = {
    version: '1.0.1',
    apps: [
        {
            name: 'api-root',
            script: './server.js',
            log_file: '/var/log/api-root.log',
            error_file: '/var/log/api-root-error.log',
            out_file: '/var/log/api-root-out.log',
            pid_file: '/var/run/api-root.pid',
            watch: true,
            watch_options: {
                followSymlinks: false,
            },
        },
        {
            name: 'admin-services',
            script: './admin/AdminService.js',
            log_file: '/var/log/admin-service.log',
            error_file: '/var/log/admin-service-error.log',
            out_file: '/var/log/admin-service-out.log',
            pid_file: '/var/run/admin-service.pid',
            watch: true,
        },
        {
            name: 'turtle-services',
            script: './turtlerace/TurtleService.js',
            log_file: '/var/log/turtle-service.log',
            error_file: '/var/log/turtle-service-error.log',
            out_file: '/var/log/turtle-service-out.log',
            pid_file: '/var/run/turtle-service.pid',
            watch: true,
        },
        {
            name: 'scissors-services',
            script: './scissors/ScissorsService.js',
            log_file: '/var/log/scissors-service.log',
            error_file: '/var/log/scissors-service-error.log',
            out_file: '/var/log/scissors-service-out.log',
            pid_file: '/var/run/scissors-service.pid',
            watch: true,
        },
        {
            name: 'mines-services',
            script: './mines/MinesService.js',
            log_file: '/var/log/mines-service.log',
            error_file: '/var/log/mines-service-error.log',
            out_file: '/var/log/mines-service-out.log',
            pid_file: '/var/run/mines-service.pid',
            watch: true,
        },
        {
            name: 'chatroom-services',
            script: './userchat/UserChatService.js',
            log_file: '/var/log/chatroom-service.log',
            error_file: '/var/log/chatroom-service-error.log',
            out_file: '/var/log/chatroom-service-out.log',
            pid_file: '/var/run/chatroom-service.pid',
            watch: true,
        },
        {
            name: 'manage-services',
            script: './management/ManagementService.js',
            log_file: '/var/log/manage-service.log',
            error_file: '/var/log/manage-service-error.log',
            out_file: '/var/log/manage-service-out.log',
            pid_file: '/var/run/manage-service.pid',
            watch: true,
        },
        {
            name: 'dice-services',
            script: './dice/DiceService.js',
            log_file: '/var/log/dice-service.log',
            error_file: '/var/log/dice-service-error.log',
            out_file: '/var/log/dice-service-out.log',
            pid_file: '/var/run/dice-service.pid',
            watch: true,
        },
        {
            name: 'slot-services',
            script: './slot/SlotService.js',
            log_file: '/var/log/slot-service.log',
            error_file: '/var/log/slot-service-error.log',
            out_file: '/var/log/slot-service-out.log',
            pid_file: '/var/run/slot-service.pid',
            watch: true,
        },
        {
            name: 'plinko-services',
            script: './plinko/PlinkoService.js',
            log_file: '/var/log/plinko-service.log',
            error_file: '/var/log/plinko-service-error.log',
            out_file: '/var/log/plinko-service-out.log',
            pid_file: '/var/run/plinko-service.pid',
            watch: true,
        },
        {
            name: 'crash-services',
            script: './crash/CrashService.js',
            log_file: '/var/log/crash-service.log',
            error_file: '/var/log/crash-service-error.log',
            out_file: '/var/log/crash-service-out.log',
            pid_file: '/var/run/crash-service.pid',
            watch: true,
        }
    ],
};
